import enum

class Event(enum.Enum):
    ON_START = 0
    ON_STOP = 1
    ON_DATA_RECEIVE = 2
    ON_MESSAGE = 3
    ON_USER_LOGIN = 4
    ON_USER_REGISTER = 5
    ON_CLIENT_CONNECT = 6
    ON_OTP_SENT = 7
    ON_CLIENT_DISCONNECT = 8
    ON_USER_PASSWORD_INCORRECT = 9
    ON_MAIL_ID_DOESNT_EXIST = 10
    ON_MESSAGE_SEND_FAILED = 11
    ON_REGISTER_FAIL_MAIL_EXISTS = 12
    ON_REGISTER_FAIL = 13
    ON_OTP_INCORRECT = 14

